spring:
  profiles:
    active: real #local,dev,real

  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: #DB 접속
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ilhan-mysql.czns5m6kktdd.ap-northeast-2.rds.amazonaws.com:3306/algoreview?useSSL=false
    username: root
    password: ilhan0422
    hikari: #커넥션풀
      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size: 10 #최대 커넥션 개수 설정
      max-lifetime: 1800000 #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명시간 1,800초(30분)


  #JPA
  jpa:
    properties:
      hibernate:
        show_sql: true # SQL문 출력

logging:
    level:
      # hibernate 가 남기는 모든 로그가 debug모드로 설정
      # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql: trace # 실제 들어가는 파라미터값 찍어주는 설정


mybatis: #mybatis 설정
  type-aliases-package: algo review.**.vo
  mapper-locations: algo review/**/dao/*.xml
jasypt:

server:
  port: 8002
  address: 0.0.0.0 # IPv4 주소를 통한 연결을 허용 / 안적으면 IPv4, IPv6 모두 포함
  servlet:
    context-path: /
    encoding:
      enabled: true # http 인코딩 지원를 활성화할지 여부
      charset: UTF-8
      force: true



